export const REQUEST_GET_COMMENTS = 'REQUEST_GET_COMMENTS';
export const RESPONSE_GET_COMMENTS = 'RESPONSE_GET_COMMENTS';
export const ERROR_GET_COMMENTS = 'ERROR_GET_COMMENTS';
export const SWITCH_IS_FAVOURITE = 'SWITCH_IS_FAVOURITE';
export const ADD_COMMENT = 'ADD_COMMENT';